version: '3.9'

services:
  main-app:
    working_dir: /app/src
    environment:
      - PYTHONPATH=/app/src
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    command: uvicorn --factory main:create_app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - "5433:5432"

volumes:
  pgdata:
  rabbitmq-data:
